config/routes.rb
Rails.application.routes.draw do

  get 'likes/index'
  get 'likes/show'
  get 'likes/new'
  get 'likes/create'
  get 'likes/destroy'
  # Specify what Rails should route '/'. The root route only routes GET requests to the action > https://edgeguides.rubyonrails.org/routing.html
  root 'home#show' #idem que root to: 'home#index'

  # routes dont le controller ne manipule pas de données en base (pas besoin de méthodes CRUD)
  get 'home', to: 'home#show'
  get 'welcome/:user_first_name', to: 'welcome#show'
  get 'team', to: 'team#show'
  get 'contact', to: 'contact#show'

  # routes dont le controller manipule des données en base ou des données temporaires (via méthodes CRUD)
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :gossips do 
    resources :comments, except: [:index, :show]
    resources :likes, only: [:new, :create, :destroy]
  end
  resources :cities
  resources :profile, only: [:show, :edit, :update, :destroy]
  
end

# NB : Rails routes are matched in the order they are specified > https://edgeguides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name, presence: true

  #validates :zip_code,
  #  presence: true
  #  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "Please enter a valid french zip code" } 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user

  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tag_joins
  has_many :tags, through: :gossip_tag_joins
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { in: 3..20 }
  validates :content, presence: true
  validates :user_id, presence: true 
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User" #indique que PrivateMessage appartient à un sender, qui est en fait de la classe User
  belongs_to :recipient, class_name: "User" #indique que PrivateMessage appartient à un recipient, qui est en fait de la classe User
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tag_joins
  has_many :gossips, through: :gossip_tag_joins
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage" # indique que le model User has_many sent_messages. Ces messages envoyés correspondent à la colonne sender_id de la classe PrivateMessage >>> permet de faire des méthodes .sender et .sent_messages
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage" # indique que le model User has_many received_messages. Ces messages reçus correspondent à la colonne recipient_id de la classe PrivateMessage >>> permet de faire des méthodes .recipient et received_messages
  
  has_secure_password #indiquer que bcrypt est en charge de gérer et hasher les mots de passe
  
  validates :password, presence: true, length: { minimum: 6 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Please enter a valid email adress" } 
  #validates :age, numericality: { only_integer: true }
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def is_permitted_comment?
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    @user = User.find(@comment.user_id)
    unless current_user == @user
      flash[:danger] = "Vous n'êtes pas autorisé(e) à modifier ou supprimer ce commentaire"
      redirect_to gossip_path(@gossip.id)
    end
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
  
  def is_permitted_gossip?
    @gossip = Gossip.find(params[:id])
    @user = User.find(@gossip.user_id)
    unless current_user == @user
      flash[:danger] = "Vous n'êtes pas autorisé(e) à modifier ou supprimer ce gossip"
      redirect_to gossip_path(@gossip.id)
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user) # à appeler à la page login mais aussi juste après la création d'un nouvel utilisateur (par exemple).
    session[:user_id] = user.id
  end

  def current_user # retourner l'instance de User contenant les infos de ton utilisateur connecté
    User.find_by(id: session[:user_id])
  end

  def logged_in? #https://levelup.gitconnected.com/simple-authentication-guide-with-ruby-on-rails-16a6255f0be8  
    !current_user.nil? # autre solution >>> session[:user_id]
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Website Title -->
    <title>GossipApp</title>
    <!-- Required meta tags -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CDN : Bootstrap CSS only -->
    <!-- !!!! WARNING : ajouter les CDN BOOTSTRAP avant les autres fichiers CSS, afin que mes styles remplacent ceux de Bootstrap par défaut -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous" />
  
    <!-- Turbolink nécessaire pour faire fonctionner les liens "link_to" avec la méthode "delete" -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <!-- Navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top py-3" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="<%= root_path %>">Gossip</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto my-1 my-lg-0">
            <% if logged_in? %>
              <li class="nav-item"><%= link_to "Se déconnecter", session_path(session.id), method: :delete, class: "nav-link btn btn-outline-secondary" %></li>
            <% else %>
              <li class="nav-item"><a class="nav-link" href="<%= team_path %>">La Team Gossip</a></li>
              <li class="nav-item"><a class="nav-link" href="<%= contact_path %>">Nous contacter</a></li>
              <li class="nav-item">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Connexion</button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="<%= new_session_path %>">Se connecter</a>
                    <a class="dropdown-item" href="<%= new_user_path %>">S'inscrire</a>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <body>
    <%= yield %>

    <!-- Footer-->
    <footer class="bg-light py-3">
      <div class="container px-4 px-lg-5">
        <div class="small text-center text-muted">Copyright &copy; 2021 - Kev@THP</div>
      </div>
    </footer>

    <!-- Optional JavaScript to put just before </body> -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>